version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    restart: always
    volumes:
      - ./.docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: ${APP_NAME}_php
    build:
      context: .docker/services/php
    environment:
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
      XDEBUG_CONFIG: "ide_key=${XDEBUG_IDE_KEY} client_host=${XDEBUG_CLIENT_HOST} start_with_request=${XDEBUG_START_WITH_REQUEST}"
    volumes:
      - ./:/app
      - ./.docker/services/php/ini/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/services/php/ini/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./.docker/services/php/ini/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - default

  redis:
    container_name: ${APP_NAME}_redis
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

networks:
  default:
    name: ${APP_NAME}
