version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    restart: always
    volumes:
      - ./.docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: ${APP_NAME}_php
    build:
      args:
        user: a
        uid: 1000
      context: .docker/services/php
      dockerfile: Dockerfile
    environment:
      - XDEBUG_SESSION=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./:/app
#      - ./.docker/services/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/services/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - default

  redis:
    container_name: ${APP_NAME}_redis
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

networks:
  default:
    name: ${APP_NAME}
