version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: wic_api_nginx
    restart: always
    volumes:
      - ./.docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: wic_api_php
    build:
      args:
        user: a
        uid: 1000
      context: .docker/services/php
      dockerfile: Dockerfile
    environment:
      - XDEBUG_SESSION=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./:/app
#      - ./.docker/services/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/services/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - default

  redis:
    container_name: wic_api_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

networks:
  default:
    name: wic_api
