name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      -main
      -dev

jobs:
  tests:
    name: Tests with php8.3
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Setup redis
        uses: chenjuneking/redis-setup-action@v1
          with:
            containerName: wic_api_redis
            hostPort: 6379
            containerPort: 6379
            password: password

      - name: Run tests with coverage results
        run: vendor/bin/phpunit --coverage-clover ./tests/_output/clover.xml
