name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Tests with php8.3
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .env
        run: cp ./.env.example ./.env

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: php
          command: |
            cp ./phpstan.neon.dist ./phpstan.neon
            composer install
            ./vendor/bin/phpunit --coverage-text
