name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Tests with php8.3
    runs-on: ubuntu-latest
    continue-on-error: false
    services:
      redis:
        image: redis:latest
        ports:
          - 6379

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

#      - name: Prepare the application
#        run: php -r "copy('.env.example', '.env');"

#      - name: Run PHPUnit tests with coverage results
#        run: vendor/bin/phpunit --coverage-clover ./tests/_output/clover.xml

      - name: Temp
        run: |
          curl google.com

#      - name: Run Codeception tests
#        run: vendor/bin/codecept -c codeception-gh-actions.yml run
